version: '3'

services:
  build_image:
    build:
      context: .
      dockerfile: Dockerfile
    command: echo "Building API Docker image"

  run_api:
    build: .
    command: bash -c "uvicorn api.main:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    depends_on:
      - build_image

  run_tests:
    build: .
    command: pytest -v api/tests --disable-warnings
    depends_on:
      - run_api